import { Product } from "./types";

// ---------------------------------------------------------------------------
// Default catalog. This seeds localStorage on first load. The admin
// dashboard can add/edit/delete on top of this, all persisted client-side.
// ---------------------------------------------------------------------------

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: "p1",
    name: "Luxury Silk Scarf",
    variant: "Navy",
    price: 85000,
    oldPrice: 120000,
    category: "Silk scarves",
    image: "https://placehold.co/400x500/1A2B4C/FFFFFF?text=Silk+Scarf",
    images: [
      "https://placehold.co/400x500/1A2B4C/FFFFFF?text=Silk+Scarf+1",
      "https://placehold.co/400x500/2C4270/FFFFFF?text=Silk+Scarf+2",
      "https://placehold.co/400x500/1A2B4C/FFFFFF?text=Silk+Scarf+3",
      "https://placehold.co/400x500/2C4270/FFFFFF?text=Silk+Scarf+4",
    ],
    rating: 4.6,
    reviews: 43,
    description:
      "Mulberry silk scarf in deep navy with a soft hand and subtle sheen. Quietly essential.",
    sizes: ["One Size"],
    colors: ["Navy", "Sage", "Cream"],
    stock: 24,
    onSale: true,
  },
  {
    id: "p2",
    name: "Leather Tote Bag",
    variant: "Tan",
    price: 320000,
    oldPrice: 450000,
    category: "Handbags",
    image: "https://placehold.co/400x500/A9784F/FFFFFF?text=Tote+Bag",
    images: [
      "https://placehold.co/400x500/A9784F/FFFFFF?text=Tote+Bag+1",
      "https://placehold.co/400x500/8A6440/FFFFFF?text=Tote+Bag+2",
      "https://placehold.co/400x500/A9784F/FFFFFF?text=Tote+Bag+3",
      "https://placehold.co/400x500/8A6440/FFFFFF?text=Tote+Bag+4",
    ],
    rating: 5.0,
    reviews: 152,
    description:
      "Full-grain leather tote with a sculpted silhouette. Ages beautifully with wear.",
    sizes: ["One Size"],
    colors: ["Tan", "Black", "Olive"],
    stock: 12,
    onSale: true,
  },
  {
    id: "p3",
    name: "Minimalist Smart Watch",
    price: 280000,
    oldPrice: 380000,
    category: "Watches",
    image: "https://placehold.co/400x500/1A2B4C/FFFFFF?text=Smart+Watch",
    images: [
      "https://placehold.co/400x500/1A2B4C/FFFFFF?text=Smart+Watch+1",
      "https://placehold.co/400x500/2C4270/FFFFFF?text=Smart+Watch+2",
      "https://placehold.co/400x500/1A2B4C/FFFFFF?text=Smart+Watch+3",
      "https://placehold.co/400x500/2C4270/FFFFFF?text=Smart+Watch+4",
    ],
    rating: 4.7,
    reviews: 74,
    description:
      "Clean-faced smart watch with heart-rate, sleep tracking, and a week-long battery.",
    sizes: ["Small", "Large"],
    colors: ["Black", "Silver"],
    stock: 30,
    onSale: true,
  },
  {
    id: "p4",
    name: "Gold Hoop Earrings",
    price: 95000,
    oldPrice: 140000,
    category: "Jewelry",
    image: "https://placehold.co/400x500/D4AF37/1A2B4C?text=Hoop+Earrings",
    images: [
      "https://placehold.co/400x500/D4AF37/1A2B4C?text=Hoop+Earrings+1",
      "https://placehold.co/400x500/C49B2F/1A2B4C?text=Hoop+Earrings+2",
      "https://placehold.co/400x500/D4AF37/1A2B4C?text=Hoop+Earrings+3",
      "https://placehold.co/400x500/C49B2F/1A2B4C?text=Hoop+Earrings+4",
    ],
    rating: 4.8,
    reviews: 96,
    description:
      "18k gold-plated hoops with a featherweight feel. Everyday statement jewelry.",
    sizes: ["Small", "Medium", "Large"],
    colors: ["Gold"],
    stock: 40,
    onSale: true,
  },
  {
    id: "p5",
    name: "UV400 Aviator Sunglasses",
    price: 120000,
    oldPrice: 180000,
    category: "Sunglasses",
    image: "https://placehold.co/400x500/1A2B4C/FFFFFF?text=Aviators",
    images: [
      "https://placehold.co/400x500/1A2B4C/FFFFFF?text=Aviators+1",
      "https://placehold.co/400x500/2C4270/FFFFFF?text=Aviators+2",
      "https://placehold.co/400x500/1A2B4C/FFFFFF?text=Aviators+3",
      "https://placehold.co/400x500/2C4270/FFFFFF?text=Aviators+4",
    ],
    rating: 4.5,
    reviews: 61,
    description:
      "Full UV400 protection aviators with a polished metal frame and gradient lens.",
    sizes: ["One Size"],
    colors: ["Gold/Green", "Black/Grey"],
    stock: 18,
    onSale: true,
  },
  {
    id: "p6",
    name: "iPhone 15 Pro Case",
    variant: "Black",
    price: 65000,
    oldPrice: 90000,
    category: "Phone cases",
    image: "https://placehold.co/400x500/111111/FFFFFF?text=Phone+Case",
    images: [
      "https://placehold.co/400x500/111111/FFFFFF?text=Phone+Case+1",
      "https://placehold.co/400x500/222222/FFFFFF?text=Phone+Case+2",
      "https://placehold.co/400x500/111111/FFFFFF?text=Phone+Case+3",
      "https://placehold.co/400x500/222222/FFFFFF?text=Phone+Case+4",
    ],
    rating: 4.4,
    reviews: 38,
    description:
      "Slim protective case with a soft-touch matte finish and reinforced corners.",
    sizes: ["iPhone 15", "iPhone 15 Pro", "iPhone 15 Pro Max"],
    colors: ["Black", "Navy", "Clear"],
    stock: 60,
    onSale: true,
  },
  {
    id: "p7",
    name: "USB-C Fast Charger 20W",
    price: 75000,
    oldPrice: 110000,
    category: "Chargers/cables",
    image: "https://placehold.co/400x500/2E6F40/FFFFFF?text=Fast+Charger",
    images: [
      "https://placehold.co/400x500/2E6F40/FFFFFF?text=Fast+Charger+1",
      "https://placehold.co/400x500/3F9457/FFFFFF?text=Fast+Charger+2",
      "https://placehold.co/400x500/2E6F40/FFFFFF?text=Fast+Charger+3",
      "https://placehold.co/400x500/3F9457/FFFFFF?text=Fast+Charger+4",
    ],
    rating: 4.6,
    reviews: 52,
    description:
      "Compact 20W USB-C wall charger — fast, safe charging for phones and earbuds.",
    sizes: ["One Size"],
    colors: ["White", "Black"],
    stock: 50,
    onSale: true,
  },
  {
    id: "p8",
    name: "Wireless Bluetooth Earphones",
    price: 180000,
    oldPrice: 250000,
    category: "Earphones",
    image: "https://placehold.co/400x500/1A2B4C/FFFFFF?text=Earphones",
    images: [
      "https://placehold.co/400x500/1A2B4C/FFFFFF?text=Earphones+1",
      "https://placehold.co/400x500/2C4270/FFFFFF?text=Earphones+2",
      "https://placehold.co/400x500/1A2B4C/FFFFFF?text=Earphones+3",
      "https://placehold.co/400x500/2C4270/FFFFFF?text=Earphones+4",
    ],
    rating: 4.7,
    reviews: 88,
    description:
      "True wireless earbuds with active noise cancellation and a 30-hour case battery.",
    sizes: ["One Size"],
    colors: ["Black", "White"],
    stock: 35,
    onSale: true,
  },
  {
    id: "p9",
    name: "10000mAh Power Bank Slim",
    price: 130000,
    oldPrice: 190000,
    category: "Power banks",
    image: "https://placehold.co/400x500/1A2B4C/FFFFFF?text=Power+Bank",
    images: [
      "https://placehold.co/400x500/1A2B4C/FFFFFF?text=Power+Bank+1",
      "https://placehold.co/400x500/2C4270/FFFFFF?text=Power+Bank+2",
      "https://placehold.co/400x500/1A2B4C/FFFFFF?text=Power+Bank+3",
      "https://placehold.co/400x500/2C4270/FFFFFF?text=Power+Bank+4",
    ],
    rating: 4.5,
    reviews: 47,
    description:
      "Pocket-slim 10000mAh power bank with dual output for charging on the go.",
    sizes: ["One Size"],
    colors: ["Black", "White"],
    stock: 28,
    onSale: true,
  },
  {
    id: "p10",
    name: "Rose Quartz Face Roller",
    price: 55000,
    oldPrice: 80000,
    category: "Small beauty/lifestyle accessories",
    image: "https://placehold.co/400x500/E8B4B8/1A2B4C?text=Face+Roller",
    images: [
      "https://placehold.co/400x500/E8B4B8/1A2B4C?text=Face+Roller+1",
      "https://placehold.co/400x500/D8A4A8/1A2B4C?text=Face+Roller+2",
      "https://placehold.co/400x500/E8B4B8/1A2B4C?text=Face+Roller+3",
      "https://placehold.co/400x500/D8A4A8/1A2B4C?text=Face+Roller+4",
    ],
    rating: 4.6,
    reviews: 29,
    description:
      "Genuine rose quartz facial roller for a calming, de-puffing skincare ritual.",
    sizes: ["One Size"],
    colors: ["Rose Quartz"],
    stock: 45,
    onSale: true,
  },
];

export const CATEGORIES: Product["category"][] = [
  "Silk scarves",
  "Handbags",
  "Watches",
  "Jewelry",
  "Sunglasses",
  "Phone cases",
  "Chargers/cables",
  "Earphones",
  "Power banks",
  "Small beauty/lifestyle accessories",
];
